title: Satellite Imagery Downloader
description: automated downloading, assembling, and georeferencing map tiles from various providers (Google, OSM, Esri, etc.)
remote_theme: https://github.com/JV-conseil/jekyll-theme-read-the-docs
